/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-data-jpa:2.7.6")
    api("org.springframework.boot:spring-boot-starter-web:2.7.6")
    api("org.springframework.boot:spring-boot-starter-security:2.7.6")
    api("com.fasterxml.jackson.module:jackson-module-kotlin:2.13.4")
    api("org.jetbrains.kotlin:kotlin-reflect:1.7.10")
    api("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10")
    api("org.springframework.security:spring-security-oauth2-client:5.7.3")
    api("dev.kord:kord-core:0.8.0-M15")
    api("org.jetbrains.kotlinx:kotlinx-html-jvm:0.8.0")
    runtimeOnly("org.springframework.boot:spring-boot-devtools:2.7.6")
    runtimeOnly("org.postgresql:postgresql:42.3.8")
    testImplementation("io.mockk:mockk-jvm:1.13.2")
}

group = "su.skaard"
version = "0.0.1-SNAPSHOT"
description = "skaard"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
