import org.gradle.kotlin.dsl.apply
import org.gradle.kotlin.dsl.`java-library`

/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "skaard"

pluginManagement {
    val kotlinVersion: String by settings
    val springBootVersion: String by settings

    plugins {
        kotlin("jvm") version kotlinVersion apply false
        kotlin("plugin.spring") version kotlinVersion apply false
        kotlin("plugin.jpa") version kotlinVersion apply false
        id("org.springframework.boot") version springBootVersion apply false
        id("io.spring.dependency-management") version "1.1.0" apply false
        `maven-publish` apply false
        `java-library` apply false
    }
}

include("skaard-core")
include("skaard-channel-presence")
//include("skaard-template-module")